### ISSUE TITLE
No real server-to-server users API calls possible independent of user interaction

### ISSUE THREAD

**Issue by alexmerz** [remp2020/crm-users-module#15]
Hi,

I'm using the Users API to synchronize the user and subscription states between REMP and our own existing CRM platform.
There seems to be no way to receive an authorization token for an customer without providing email & password. This leads to trouble in any situation where an actions needs to be done on behalf of the customer, but the customer itself (and its clear text password) is not present in the process, for example an action triggered by a cronjob of our CRM.

The only workaround so far seems to be:
- When customer logs in via our CRM, also login to REMP via API-Login
- store the customer authorization token somewhere in our CRM backend
- hope the customer does not logout via UI, or token becomes invalid by other reasons
- use the token from the CRM backend to make API requests when neccessary

The workaround does not look very stable.

Is there any chance to actually get something like
api/v1/users/request-authorize-token?user_id=xxxxx (with server bearer token)
or
api/v1/user/request-permanent-authorize-token (with user authorization token from the Login via UI)

the receive a permanent authorization token not bound to any UI interaction for server-to-server-communication.

Best
Alexander Merz

**Comment by rootpd** [comment]
Hi Alex,

first of all thanks for using the CRM and sorry for the waiting!. I needed to test a bit before I responded to you.

**Context.** (Don't worry, I'll get to the point :)). The scenario you describe is something, that we don't want developers encourage to get into. Keeping two systems in sync is always a pain and we usually recommend one of two approaches:

- Either push anything new from CRM to your system right when it happens. This includes couple of new event handlers that would call your APIs whenever there's a new/updated subscription.
- Or, on frontend, read anything from CRM on-demand, with user's access token. On backend, use CRM's admin to administer the subscriptions.

I understand that's not always what you _can_ do. To solve your issue, I can think of two options:

**OPTION 1.** The thing I was testing was enabling a feature, that wasn't used for quite a while allowing you exactly what you needed. It works, but only for some API endpoints since it's not a fully-enabled feature. You can try it:

1. Enable new user authorizator by adding this to your `config.local.neon`:

```neon
services:
	# ...
	userTokenAuthorization:
		setup:
			- registerAuthorizator('serviceFOO', Crm\UsersModule\Auth\ServiceTokenAuthorization())
```

2. Try to call the API you want with `user_id=XXX` parameter and `source=serviceFOO` (whatever you used above) parameter. It will tell the system to use this backend authorization and it will authorize the user.

I tested it against the API for listing the subscriptions and it fails on a bug which we'll handle in the next release. If you only need to use subscription listin API, this might get you covered. If you need more, it might not be enough.

**OPTION 2.** You can create the API call you're writing about yourself and extend the CRM. In fact, it's something we encourage publishers to do. Please read about adding your own API endpoints to CRM at https://gitlab.com/remp/crm-skeleton#registerapicalls. 

You can use https://github.com/remp2020/crm-users-module/blob/master/src/Api/UsersLoginHandler.php as a base implementation, remove everything that doesn't need to be there, and return the access token you need. Very simplified, it might look like this:

```php
<?php

namespace Crm\UsersModule\Api;

use Crm\ApiModule\Api\ApiHandler;
use Crm\ApiModule\Params\InputParam;
use Crm\ApiModule\Params\ParamsProcessor;
use Crm\UsersModule\Repository\AccessTokensRepository;
use Nette\Http\Response;
use Nette\Security\AuthenticationException;
use Tomaj\NetteApi\Response\JsonApiResponse;
use Tomaj\NetteApi\Response\ResponseInterface;

class UsersLoginHandler extends ApiHandler
{
    private $accessTokensRepository;

    public function __construct(
        AccessTokensRepository $accessTokensRepository
    ) {
        $this->accessTokensRepository = $accessTokensRepository;
    }

    public function params(): array
    {
        return [
            new InputParam(InputParam::TYPE_POST, 'user_id', InputParam::REQUIRED)
        ];
    }

    public function handle(array $params): ResponseInterface
    {
        $lastToken = $this->accessTokensRepository->allUserTokens($params['user_id'])->limit(1)->fetch();
        $result = [
            'status' => 'ok',
            'token' => $lastToken->token ?? null,
        ];

        $response = new JsonApiResponse(Response::S200_OK, $result);
        return $response;
    }
}
```

**Comment by rootpd** [comment]
Correction, **Option 1** is usable, I was testing it against one of our own internal APIs :).

**Comment by mmacsodi** [comment]
hi @rootpd,

I tried **Option 1** with the user info API, and it does not work because it gets the user from the token instead of `getAuthorizedUsers`. I resolved it by creating a new authorizator which uses the `BearerTokenAuthorization` and creates a "fake" token with a user property:

```php
    public function authorized($resource = Authorizator::ALL): bool
    {
        $userId = $this->request->getQuery('user_id');
        if ($userId) {
            $this->authorizator = $this->bearerTokenAuthorization;
            $isAuthorized = $this->authorizator->authorized($resource);
            if ($isAuthorized) {
                $user = $this->usersRepository->find($userId);
                if ($user) {
                    $this->authorizedUsers[] = $this->usersRepository->find($userId);

                    $token = new \stdClass();
                    $token->user = $user;
                    $this->authorizedData['token'] = $token;

                    return true;
                }
            }
        }

        return false;
    }
```

**Comment by rootpd** [comment]
Yes, unfortunately we introduced the `getAuthorizedUsers()` and its interface much later than we created the base API calls - like the user info API. The authorization you created is basically OK. It's just not something that we'd put into the open source module and encourage people to use :).

If it solves the issue, then just go ahead :+1: .

Maybe, just to be sure, you could load actual (random) `access_token` instead of using `stdClass`.

**Comment by alexmerz** [comment]
Thanks for the feedback and help!

Best regards
Alex
